#+TITLE: Glossary

* EXPORT CONFIG :ignore:noexport:
#+DESCRIPTION: Descriptive text
#+KEYWORDS: protocol
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS: tex:t todo:t pri:nil tags:t texht:nil
#+OPTIONS: author:nil creator:nil email:nil date:nil
#+EXPORT_FILE_NAME: ../glossary.rst


* Raspberry Pi Wordlist
#+begin_glossary
SoC
    Stands for System On a Chip and is used to describe small boards that
    function as small computers.

GPIO
    General Purpose Input/Output pins are connections on microprocessors or
    SoC's that allows for interfacing with arbitrary electronic components.

Raspbian
    A Linux distrobution, based on the popular Debian, made and
    optimized for the Raspberry PI.

JeOS
    (Pronounced "juice") Stands for "Just enough Operating System" and is a
    paradigm for designing systems that focus on just doing one particular thing
    effectively. This is especially relevant in the context of embedded systems
    where resources are limited. A general purpose operating system has a huge
    amount of features and subsystems to accomedate various use cases. A
    JeOS aims to strip away as much as possible, leaving just the absolute
    minimum required to effectively perform the task it's designed for.

RetroPie
    RetroPI is a [[:term:JeOS]] that turns the RPi into an arcade machine. It
    has emulators for a bunch of legacy consoles and computers. It's very easy
    to set up.

ROM
    Read-Only Memory is a type of non-volatile memory circuit that, as opposed to RAM,
    can only be read from. Old console- and computer games would be stored on
    ROM-chips packaged in cartridges which could be inserted into the machine.
    Today the word ROM often refers to ROM-files which are digitalized versions
    made for an emulator. A ROM-file contains the exact same data as would be
    found on the physical chip.

Disk image
    A disk image, is a file containing the contents of a disc volume or storage
    device, such as a hard drive or flash drive. They are commonly used for
    installation media.

#+end_glossary


* Software Wordlist
#+begin_glossary
JSON
    Javascript Object Notiation is, despite its name, a language independant
    markup and serialization format. Commonly used for configuration and as an
    intermediary for interprocess communication.
#+end_glossary
