#+TITLE: Pypes documentation
#+AUTHOR: Silas Wagner
#+EMAIL: silaswagner.dev@gmail.com

* EXPORT CONFIG :ignore:noexport:
#+OPTIONS: H:4 num:nil toc:nil ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS: tex:t todo:t pri:nil tags:t texht:nil
#+OPTIONS: author:nil creator:nil email:nil date:nil
#+EXPORT_FILE_NAME: ../index.rst

* TOC :ignore:
#+begin_export rst
.. toctree::
   :hidden:

   Workshop<workshop>
   Hardware<raspberry>
   The Pypes software and protocol<pypes>
   Contribution guidelines<contributing>
   Wordlist<glossary>
#+end_export

* Overview of the project
This project was made as part of a workshop for young students.
We work shifts on the project, and the general idea is that the students with
more experience introduce the next wave, and then hand it over.

The primary focus of the workshop is to give the students a taste of the
IT-professions through small exersises and projects.
A general theme for these workshops is "build an internet cafe", and most of the
activities revolve around Raspberry Pis in one way or another.

This documentation describes the hardware we've used, the software we've built,
the activities we planned and things we learned along the way.

It should be a resource that can be used to learn from and build upon, as the
project is passed on to other students.


* Contents
The documentation is organised in 4 main parts:

** [[:doc:workshop][The workshop]]
Here you can find an overview of the activities and projects that has been
prepared so far, as well as some ideas and reflection for future improvement.

** [[:doc:raspberry][The hardware]]
Still unsure if a Raspberry Pi is edible or not? Just not sure how to configure it
or where to find relevant tools and software? This is where you go for answers.

** [[:doc:pypes][The software]]
Documentation for software and scripts we developed for the workshop. Currently
there is only a server and client for a simple chat service, but hopefully this
will become a collection of all kinds of software authered by various
contributers.

** [[:doc:contributing][Contribution guidelines]]
Guidelines for contributing to the software and the documentation itself.
These are not meant to be rules or requirements, but rather help and
instructions for anyone who would like to make a contribution.

Minor software improvements, snippets of documentation and spelling corrections
are all welcome. Regardless of experience, everyone is encouraged to take part.
