#+TITLE: Workshop
#+AUTHOR: Silas Wagner
#+EMAIL: silaswagner.dev@gmail.com

* EXPORT CONFIG :ignore:noexport:
#+OPTIONS: H:4 num:nil toc:nil ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS: tex:t todo:t pri:nil tags:t texht:nil
#+OPTIONS: author:nil creator:nil email:nil date:nil
#+EXPORT_FILE_NAME: ../workshop.rst


* Intro :ignore:

Our main task through this project has been planning and preparation of
activities for the workshop. This proved to be significantly more difficult than
first anticipated; demonstrating technical subjects in a meningfully way, to an
audience with no previous experience is hard. We have had to come up with ways
to wrap technical detail in engaging material, and decide on reasonable
compromise between fun and relevance to the field.

This document describes the activities we have prepared so far, as well as
thoughts about the obstacles we faced and ideas for future improvment/expansion.

* Activities
** Short introduction to Raspberry Pi.
What is it? What can it do, and what can be said about the hardware?

See [[:doc:raspberry][The Raspberry Pi page]] for more.

** Assembling Ethernet cables.
(WIP) Each group cuts a piece of cable, and attach two RJ45 connectors.
write a small instruction thingy here.

** Testing cables and joining a local network
Once cables have been tested and verified to work, groups connect through a
switch to a local network where a chat server is running.

The server and client software is an example of something that we developed, and
it makes for a nice segway to talk a bit about networking and protocols.

See [[:doc:pypes]] for documentation of the software.

** (IDEA) Possibly some scripting related tasks
The whole theme here is setting up a netcafe, which involves configuring
several machines similarly. This can be tedious to do one by one. This would
be a perfect example of something that can be automated through scripting.

** Install RetroPie. Turn the desktop computer into a gaming system.
Following the [[:term:RetroPie]] documentation, the students will configure the machines
with a new operating system. When finished they get to play games for the
remainder of the day, so this should be scheduled to be within a
reasonable time before the end of the day.


* Ideas for improvment

#+begin_note
This is a WIP
#+end_note

* Thoughts and reflection
#+begin_note
This is a WIP
#+end_note
Learning potentially goes full circle with projects like these; we have learned
a lot from the process of planning and preparing the activities. Through the
workshop we have had opportunity to teach and demonstrate areas of our field to
the students, which in itself is an educational experience.
