name: Docs2Pages
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: abatilo/actions-poetry@v2.1.3
    - name: install
      run: poetry install
    - name: Build documentation
      run: |
        mkdir github-pages
        touch github-pages/.nojekyll
        cd docs/
        poetry run make clean
        poetry run make rst
        poetry run make html
        cp -r build/html/* ../github-pages/
    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: github-pages
        folder: github-pages
